### ISSUE TITLE
svyWebcam does not work with Ti-Client [2022.9.1.3804]

### ISSUE THREAD

**Issue by r4inX** [Servoy/svywebcam#3]
Hey guys, 
i updated my Servoy Project to Servoy 2022.09 and upgraded from NG to Ti. 
Now the svyWebcam is not working. It doesn´t even show in the form-editor.

I checked the repo and saw that the last update was on JAN/2021.
Is there a update comming soon to this component or is it deprecated now? Thas would be fatal if there is no replacement for it.

-R4IN

**Comment by paronne** [comment]
Hi R4IN,

there is a TiNG implementation for the svyWebCam but yet has to be officially released.
I have created a follow up task in our ticket system to which you can subscribe as a watcher.

https://support.servoy.com/browse/SVYX-526

Regards,
Paolo

**Comment by lvostinar** [comment]
Hi, I released the new version.
